packages:
  - "apps/*"
  - "packages/*"

overrides:
  "@esbuild-kit/core-utils@3.3.2>esbuild": 0.25.12
  nanoid@<3.3.18: 3.3.18

onlyBuiltDependencies:
  - argon2
  - esbuild
allowBuilds:
  argon2: true
  esbuild: true
minimumReleaseAgeExclude:
  - '@types/pg@8.20.4'
  - tsx@4.23.8
